version: "3.9"
services:
  client:
    container_name: "metaversus-client"
    build: "./client"
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metaversus_client.rule=Host(`metaversus.issamounejjar.live`)"
      - "traefik.http.routers.metaversus_client.entrypoints=websecure"
      - "traefik.http.routers.metaversus_client.tls.certresolver=letsencrypt"
    restart: unless-stopped

networks:
  homelab:
    external: true
